swagger: '2.0'
info:
  version: 1.0.0
  title: おすすめパスタ
paths:
  '/pasta/{date}':
    get:
      description: おすすめパスタ取得を取得する
      responses:
        '200':
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
                example: OK
              pasta_name:
                type: string
                description: パスタ
                example: ボロネーゼ
              description:
                type: string
                description: パスタ説明
                example: ひき肉をトマトやワインと一緒に煮込んだパスタのことだぞ
              comment:
                type: string
                description: 一言
                example: お肉を食べて体力をつけるぞ！
              date:
                type: string
                description: 取得した日付
                format: date
            required:
              - result
        '400':
          description: Bad Request
          schema:
            description: ''
            type: object
            properties:
              result:
                type: string
                minLength: 1
                example: NG
              error_msg:
                type: string
                minLength: 1
                example: 日付の指定が変だぞ
            required:
              - result
              - error_msg
          examples: {}
      operationId: ''
      summary: おすすめパスタ取得
      tags:
        - パスタ
    parameters:
      - type: string
        name: date
        in: path
        description: YYYY-MM-DD指定 省略時は今日日付が指定される
        format: date
tags:
  - name: パスタ
